package model;

import java.util.UUID;

/** Users entities will be used later on to access transactions and budget reports. */
public class User {
  private UUID userId;
  private String username;
  private String email;
  private double budget;
    
  // ---------- Constructors ----------
  public User() {
  }
  
  /** Create new user. Fields not passed as parameters re automatically generated by database. */
  public User(String username, String email, double budget) {
    this.username = username;
    this.email = email;
    this.budget = budget;
  }

  // ---------- Getters / Setters ----------
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }  

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public double getBudget() {
    return budget;
  }

  public void setBudget(double budget) {
    this.budget = budget;
  }
}