package dev.ase.teamproject.model;

import java.util.UUID;

/**
 * This class defines the User model used in the application.
 * A user represents an individual with an account in the system. 
 * Each user has identifying information such as a unique ID, username, 
 * email address, and a budget. The User entity serves as the foundation
 * for tracking transactions, spending summaries, and budget analytics.
 */
@SuppressWarnings({
    "PMD.ShortClassName", // Commonly used class name
    "PMD.DataClass" // Class primarily holds data
})
public class User {
  /** The unique identifier for the user. */
  private UUID userId;

  /** The display name of the user. */
  private String username;

  /** The email address of the user. */
  private String email;

  /** The total budget assigned to this user. */
  private double budget;

  /** Default constructor for User. */
  public User() {
    // no-op
  }
  
  /**
   * Constructs a new {@code User} with specified username, email, and budget.
   * The unique {@code userId} is generated by the database.
   *
   * @param username The display name of the user.
   * @param email The email address of the user.
   * @param budget The total budget assigned to this user.
   */
  public User(final String username, final String email, final double budget) {
    this.username = username;
    this.email = email;
    this.budget = budget;
  }

  public UUID getUserId() {
    return userId;
  }

  public void setUserId(final UUID userId) {
    this.userId = userId;
  }  

  public String getUsername() {
    return username;
  }

  public void setUsername(final String username) {
    this.username = username;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(final String email) {
    this.email = email;
  }

  public double getBudget() {
    return budget;
  }

  public void setBudget(final double budget) {
    this.budget = budget;
  }
}