package dev.ase.teamproject.model;

import java.util.UUID;

/**
 * This class defines the User model used in the application.
 * <p>
 *  A user represents an individual with an account in the system. Each user has identifying
 *  information such as a unique ID, username, email address, and a budget. The User entity
 *  serves as the foundation for tracking transactions, spending summaries, and budget analytics.
 * </p>
 *
 */
public class User {
  private UUID userId;
  private String username;
  private String email;
  private double budget;

  public User() {
  }
  
  /**
   * Constructs a new {@code User} with the specified username, email, and budget.
   * <p>
   *  The unique {@code userId} is expected to be generated by the database.
   * </p>
   *
   * @param username The display name of the user.
   * @param email The email address of the user.
   * @param budget The total budget assigned to this user.
   */
  public User(String username, String email, double budget) {
    this.username = username;
    this.email = email;
    this.budget = budget;
  }

  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }  

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public double getBudget() {
    return budget;
  }

  public void setBudget(double budget) {
    this.budget = budget;
  }
}